version: '3.8'
services:
  twosum_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notesdb
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
