import {
  Column,
  CreateDateColumn,
  Entity,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';

@Entity('notes') //Table name
export class Note {
  @PrimaryGeneratedColumn()
  id: number; //Primary key generated by the database

  @Column({ type: 'text' })
  title: string; //Title of the note

  @Column({ type: 'text', nullable: true })
  content: string; //Content of the note(optional)

  @Column({ default: false })
  isFinished: boolean; //If the note is finished or not

  @CreateDateColumn()
  createdAt: Date; //Date of creation (Automatic)

  @UpdateDateColumn()
  updatedAt: Date; //Date of update (Automatic)
}
